SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = moving_average.sv
TOPLEVEL = moving_average
MODULE = test_moving_average
COMPILE_ARGS = -DDUMP_WAVES
include $(shell cocotb-config --makefiles)/Makefile.sim
